config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get  'my_measurements' => 'measurements#my_measurements', :as => 'my_measurements'
  get  'enter_my_measurements' => 'measurements#enter_my_measurements', :as => 'enter_my_measurements'
  post  'process_enter_new_measurements' => 'measurements#process_enter_new_measurements', :as => 'process_enter_new_measurements'
 
  get  'dashboard' => 'homepage#dashboard', :as => 'dashboard'
  get 'my_goals' => 'goals#my_goals', :as => 'my_goals'
  get 'my_clients' => 'clients#my_clients', :as => 'my_clients'
  get 'my_workouts' => 'workouts#my_workouts', :as => 'my_workouts'
  
  
  root 'homepage#dashboard'

end

app/models/database.rb
class Database

  attr_accessor :exercises
  attr_accessor :measurements

  def initialize
    @exercises = Array.new
    @measurements = Array.new
  end

  def process_enter_new_measurements(weight, body_fat, height)
    @measurements.push([weight, body_fat, height])
  end
  
  def process_new_exercise(name, type, disc, muscle)
    @exercises.push([name, type, disc, muscle])
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :get_db_from_session
  # after_action  :store_db_in_session
  
  private
  def get_db_from_session

    @db = Database.new()
    if !session[:db].blank?
      @db = YAML.load(session[:db])
    end
  end

  public
  
  def new
  end
  
  def show
    puts("showing the progress")
  end
  
  def my_clients
      puts("displaying my clients")
  end

  def homepage
    puts("go back to the homepage")
  end
  
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :get_db_from_session
  # after_action  :store_db_in_session
  
  private
  def get_db_from_session

    @db = Database.new()
    if !session[:db].blank?
      @db = YAML.load(session[:db])
    end
  end

  public
  
  def new
  end
  
  def show
    puts("showing the progress")
  end

  def my_goals
      puts("displaying my goals")
  end
  
  def homepage
    puts("go back to the homepage")
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_action :get_db_from_session
  # after_action  :store_db_in_session
  
  private
  def get_db_from_session

    @db = Database.new()
    if !session[:db].blank?
      @db = YAML.load(session[:db])
    end
  end

  public
  
  def new
  end
  
  def show
    puts("showing the progress")
  end

  
  def dashboard
    puts("dashboard showing")
  end
  
  def my_measurement
    puts("Displaying my measurements page")
  end
  
  def my_workout
    puts("Displaying my workout page")
  end
  
  def my_goals
    puts("my recent goal")
  end 
  
  def homepage
    puts("go back to the homepage")
  end
  
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController

  before_action :get_db_from_session
  after_action  :store_db_in_session
  
  private
  
  def get_db_from_session

    @db = Database.new()

    if !session[:db].blank?
      @db = YAML.load(session[:db])
    end
  end

  def store_db_in_session

    session[:db] = @db.to_yaml
  end

  public
  
  def new
  end

  def my_measurements
    puts("Displaying my measurements page")
  end
  
  def enter_my_measurements
    puts("Displaying enter my measurements page")
  end
  
  def process_enter_new_measurements
    weight = params[:weight]
    body_fat = params[:body_fat]
    height = params[:height]
    @db.process_enter_new_measurements(weight, body_fat, height)
    
    redirect_to my_measurements_path
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  before_action :get_db_from_session
  # after_action  :store_db_in_session
  
  private
  def get_db_from_session

    @db = Database.new()
    if !session[:db].blank?
      @db = YAML.load(session[:db])
    end
  end

  public
  
  def new
  end
  
  def show
    puts("showing the progress")
  end
  
  def my_workouts
    puts("displaying my workouts")
  end

  def homepage
    puts("go back to the homepage")
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/clients/my_clients.html.erb
<p>
  My Client:
  <span class="client"><%= @db.measurements %></span>
</p>

<%= render :template => 'homepage/template' %>

app/views/game/new.html.erb
<body>
    <div class="container">
      <div id="header" class="span-24">
      </div>
      <div class="span-24">
        <%= yield %>
      </div>
      <%= form_tag my_measurements_path, :method => :get do %>
      <%= submit_tag 'My Measurements' %>
      <% end %>
      <div id="footer" class="span-24">
        <p>Project by Team Girl Scout Cookies</p>
      </div>
    </div>
  </body>

app/views/goals/my_goals.html.erb
<h2>My Goals</h2>

<%= render :template => 'homepage/template' %>

app/views/homepage/dashboard.html.erb
<%= form_tag my_goals_path, :method => :get do%>
  <%= submit_tag 'My Goals' %>
<% end %>

<%= form_tag my_measurements_path, :method => :get do%>
  <%= submit_tag 'My Measurements'  %>
<% end %>

<%= form_tag my_clients_path, :method => :get do %>
  <%= submit_tag 'My Clients' %>
<% end %>

<%= form_tag my_workouts_path, :method => :get do %>
  <%= submit_tag 'My Workouts' %>
<% end %>

<form>
      <fieldset>
        <legend>Dashboard</legend>
        <p>
          <label>my progress </label>

        </p>
      </fieldset>
    </form>

app/views/homepage/my_client.html.erb
<p>
  My Client:
  <span class="client"><%= @db.measurements %></span>
</p>

<%= render :template => 'homepage/template' %>

app/views/homepage/my_workout.html.erb
<p>
  My Workout:
  <span class="workout"><%= @db.measurements %></span>
</p>



<%= render :template => 'homepage/template' %>

app/views/homepage/template.html.erb
</h><body>
    <div class="container">
      <div id="header" class="span-24">
      </div>
      <div class="span-24">
        <%= yield %>
      </div>
      <div id="footer" class="span-24">
        <p>Project by Team Girl Scout Cookies</p>
      </div>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Measurements</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!--<%= link_to 'Home Page', '/' %>-->
    <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
    <% end %>
    
    <div class="container">
        <h>Girl Scout Cookies Exercise Tracker</h>
      </div>
      <div class="span-24">
        <%= link_to 'Home Page', '/' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/measurements/enter_my_measurements.html.erb
<h2>Enter my measurements</h2>


<%= form_tag process_enter_new_measurements_path, :method => 'post' do %>
  <%= text_field_tag 'weight', '', :size => 1, :autocomplete => 'off' %>
  <%= text_field_tag 'body_fat', '', :size => 1, :autocomplete => 'off' %>
  <%= text_field_tag 'height', '', :size => 1, :autocomplete => 'off' %>
  <%= submit_tag 'Enter' %>
<% end %>

app/views/measurements/my_measurements.html.erb
<p>
  Measurements so far:
  <span class="measurements"><%= @db.measurements %></span>
</p>

<%= form_tag enter_my_measurements_path, :method => :get do %>
  <%= submit_tag 'Enter New Measurements' %>
<% end %>

app/views/workouts/my_workouts.html.erb
<p>
  My Workout:
  <span class="workout"><%= @db.measurements %></span>
</p>



<%= render :template => 'homepage/template' %>